### PR TITLE
update docs for azure storage account

### PR DESCRIPTION
**Pull request by fmoehler**

### CODE REVIEW

**Comment by mvach** [comment]
lgtm

**Review by mvach — APPROVED** [review]

**Review by ramonskie — APPROVED** [review]
lgtm

**Review by rkoster — CHANGES_REQUESTED** [review]
Please add a note about since which version of the director this is available (requires all the other PR's to be merged...)

**Comment by mvach** [comment]
@rkoster will the next bosh release with the azure-storage integration be a minor version update to 277.5.0 (semantically I'd expect that)?  Or just a patch version update to 277.4.4?

**Comment by beyhan** [comment]
We decided to go with `278.0.0`.

**Comment by Malsourie** [comment]
Done.

**Review by rkoster — APPROVED** [review]

**Comment by beyhan** [comment]
sorry for the late question but should we add also a stemcell version to the docs because this depends also to  agent/stemcell version?

**Comment by mvach** [comment]
> sorry for the late question but should we add also a stemcell version to the docs because this depends also to agent/stemcell version?

haaa then we still have to wait for the relevant stemcell release ...

**Comment by max-soe** [comment]
Yes the storage cli was merged in [1.196](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commits/ubuntu-jammy/v1.196), latest official release is 1.181

**Comment by Malsourie** [comment]
Done. Thanks for the hints @max-soe . I did not add the stemcell version into `/content/release-blobstore.md` since it is only related to bosh cli and director.

**Comment by ramonskie** [comment]
1.196 has never been published.
so it should state the latest release [1.199](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-jammy%2Fv1.199)

**Comment by Malsourie** [comment]
Done!

> 1.196 has never been published.
> so it should state the latest release [1.199](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-jammy%2Fv1.199)

**Pull request merged**
