### PR TITLE
Update deploying-step-by-step.md

### PR DESCRIPTION
**Pull request by sepdesign**
Removing Step by Step video

### CODE REVIEW

**Comment by pivotal-madeline-preston** [comment]
I signed the CLA yesterday but today's check failed, re-signed again today. If it doesn't take I have no problems with you pushing the PR through / taking the credit.

**Comment by rkoster** [comment]
Thanks! @sepdesign

**Review by mvach — APPROVED** [review]
nice

**Comment by jpalermo** [comment]
Changes were committed so closing out. Thanks!

**Pull request closed without merging**
