### PR TITLE
Advanced usage of operator 'p'

### PR DESCRIPTION
**Pull request by giner**

### CODE REVIEW

**Comment by giner** [comment]
The related code https://github.com/cloudfoundry/bosh/blob/2ffa4734f28f1f621360102956aa326d7a7af478/src/bosh-template/lib/bosh/template/evaluation_context.rb#L59-L96

**Comment by cppforlife** [comment]
@giner im not sure it's worth encouraging this configuration, since i believe it introduces more complexity than necessary. how do you end up using these shorthands?

**Comment by giner** [comment]
> im not sure it's worth encouraging this configuration, since i believe it introduces more complexity than necessary

Agreed. This is the reason why I'd like to put them as "advanced".

> how do you end up using these shorthands?

First time I met this when trying to understand and modify one of bosh releases and didn't find anything about this in docs. So I had to dig into the code.

Another time we wanted to make backward compatible change in our bosh release and with that syntax it was very simple and easy to read (considering that this is included in docs) change.

**Comment by CAFxX** [comment]
> how do you end up using these shorthands?

A common scenario is autodetecting VM properties:

```
<%= p("thread.max", cpu_cores * 2) %>
```

(sure, it can also be written with `if_p`)

Another good reason to document it is, as @giner says, deciphering the behavior of some of the Cloud Foundry bosh releases, where these shorthands are sometimes used.

I agree we could add a note discouraging their use, but they should be documented nevertheless.

**Comment by giner** [comment]
How often it is used even though it is not documented:
```
cf-release$ find -name "*.erb" | xargs grep '[^_]p([^)]\+,[^)]\+)'
./jobs/haproxy/templates/cert.pem.erb:<%= p("ha_proxy.ssl_pem", "") %>
./src/postgres-release/jobs/postgres/templates/postgresql.conf.erb:max_connections = <%= p("databases.max_connections", 500) %>
./src/postgres-release/jobs/postgres/templates/utils.sh.erb:  <% p("databases.roles", []).each do |role| %>
./src/postgres-release/jobs/postgres/templates/utils.sh.erb:  <% p("databases.databases", []).each do |database| %>
./src/postgres-release/jobs/postgres/templates/pg_hba.conf.erb:<% p("databases.roles", []).each do |role| %>
./src/postgres-release/jobs/postgres/templates/pg_ident.conf.erb:<% p("databases.roles", []).each do |role| %>
./src/uaa-release/jobs/uaa/templates/bin/uaa.erb:<% if p('uaa.ldap.sslCertificate', nil) || p('login.ldap.sslCertificate', nil) %>
./src/uaa-release/jobs/uaa/templates/bin/configure_newrelic.erb:  hasnewreliclic = p('uaa.newrelic.common.license_key', nil) || p('uaa.newrelic.'+newrelicenv+'.license_key', '').to_s.strip.length > 0
./src/uaa-release/jobs/uaa/templates/config/newrelic.yml.erb:    hasnewreliclic = p('uaa.newrelic.common.license_key', nil) || p('uaa.newrelic.'+newrelicenv+'.license_key', '').to_s.strip.length > 0
./src/uaa-release/jobs/uaa/templates/config/newrelic.yml.erb:<%= require 'yaml'; YAML.dump(newrelic.reject {|x,_| x == 'environment'}) %><%
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:    p(property, nil)
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:    YAML.dump(params, :indentation => 2)
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:  issuer_uri = p('uaa.issuer', p('uaa.url'))
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'minLength' => p('uaa.client.secret.policy.minLength', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'maxLength' => p('uaa.client.secret.policy.maxLength', 255),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireUpperCaseCharacter' => p('uaa.client.secret.policy.requireUpperCaseCharacter', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireLowerCaseCharacter' => p('uaa.client.secret.policy.requireLowerCaseCharacter', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireDigit' => p('uaa.client.secret.policy.requireDigit', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireSpecialCharacter' => p('uaa.client.secret.policy.requireSpecialCharacter', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'expireSecretInMonths' => p('uaa.client.secret.policy.expireSecretInMonths', 0)
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'minLength' => p('uaa.client.secret.policy.global.minLength', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'maxLength' => p('uaa.client.secret.policy.global.maxLength', 255),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireUpperCaseCharacter' => p('uaa.client.secret.policy.global.requireUpperCaseCharacter', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireLowerCaseCharacter' => p('uaa.client.secret.policy.global.requireLowerCaseCharacter', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireDigit' => p('uaa.client.secret.policy.global.requireDigit', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'requireSpecialCharacter' => p('uaa.client.secret.policy.global.requireSpecialCharacter', 0),
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:        'expireSecretInMonths' => p('uaa.client.secret.policy.global.expireSecretInMonths', 0)
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:  login_entityId = p(['login.saml.entityid'], login_entityBaseUrl.sub(/^http.*:\/\//,''))
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:  login_authorizeUrl = "#{p('uaa.url', entity_base_url_fallback)}/oauth/authorize"
./src/uaa-release/jobs/uaa/templates/config/uaa.yml.erb:  login_url = p('login.url', login_entityBaseUrl)
./src/uaa-release/jobs/uaa_postgres/templates/pg_hba.conf.erb:<% p("postgres.roles", []).each do |role| %>
./src/uaa-release/jobs/uaa_postgres/templates/postgres_start.sh.erb:<% p("postgres.roles", []).each do |role| %>
./src/uaa-release/jobs/uaa_postgres/templates/postgres_start.sh.erb:<% p("postgres.databases", []).each do |database| %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/uaa_ca.crt.erb:<%= p("uaa.ca_cert", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.resource_pool.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.resource_pool.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.packages.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.packages.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.droplets.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.droplets.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.buildpacks.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.buildpacks.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb:  temporary_oci_buildpack_mode: <%= p("cc.diego.temporary_oci_buildpack_mode", nil) %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/credhub_ca.crt.erb:<%= p("credhub_api.ca_cert", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/db_ca.crt.erb:<%= p('ccdb.ca_cert', '') %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_clock/templates/stacks.yml.erb:stacks: <%= p("cc.stacks", []).to_yaml.gsub("---", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/uaa_ca.crt.erb:<%= p("uaa.ca_cert", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.resource_pool.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.resource_pool.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.packages.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.packages.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.droplets.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.droplets.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.buildpacks.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.buildpacks.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb:  temporary_oci_buildpack_mode: <%= p("cc.diego.temporary_oci_buildpack_mode", nil) %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/db_ca.crt.erb:<%= p('ccdb.ca_cert', '') %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/setup_local_blobstore.sh.erb:  <% if p("cc.packages.blobstore_type").downcase == "fog" && p("cc.packages.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/setup_local_blobstore.sh.erb:  <% if p("cc.resource_pool.blobstore_type").downcase == "fog" && p("cc.resource_pool.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/setup_local_blobstore.sh.erb:  <% if p("cc.droplets.blobstore_type").downcase == "fog" && p("cc.droplets.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/setup_local_blobstore.sh.erb:  <% if p("cc.buildpacks.blobstore_type").downcase == "fog" && p("cc.buildpacks.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_worker/templates/stacks.yml.erb:stacks: <%= p("cc.stacks", []).to_yaml.gsub("---", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/uaa_ca.crt.erb:<%= p("uaa.ca_cert", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:reserved_private_domains: <%= p("cc.reserved_private_domains", nil) %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  app_ssh_host_key_fingerprint: <%= p("app_ssh.host_key_fingerprint", nil) %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  min_cli_version: <%= p("cc.min_cli_version", nil) %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  min_recommended_cli_version: <%= p("cc.min_recommended_cli_version", nil) %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:<% uaa_url = p("uaa.url", "#{scheme}://uaa.#{system_domain}")
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:   login_url = p("login.url", "#{scheme}://login.#{system_domain}") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.resource_pool.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.resource_pool.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.packages.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.packages.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.droplets.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.droplets.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_connection: <%= p("cc.buildpacks.fog_connection", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  fog_aws_storage_options: <%= p("cc.buildpacks.fog_aws_storage_options", {}).to_json %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb:  temporary_oci_buildpack_mode: <%= p("cc.diego.temporary_oci_buildpack_mode", nil) %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/credhub_ca.crt.erb:<%= p("credhub_api.ca_cert", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/db_ca.crt.erb:<%= p("ccdb.ca_cert", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/setup_local_blobstore.sh.erb:  <% if p("cc.packages.blobstore_type").downcase == "fog" && p("cc.packages.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/setup_local_blobstore.sh.erb:  <% if p("cc.resource_pool.blobstore_type").downcase == "fog" && p("cc.resource_pool.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/setup_local_blobstore.sh.erb:  <% if p("cc.droplets.blobstore_type").downcase == "fog" && p("cc.droplets.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/setup_local_blobstore.sh.erb:  <% if p("cc.buildpacks.blobstore_type").downcase == "fog" && p("cc.buildpacks.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/perm_ca.crt.erb:<% p("perm.ca_certs", []).each do |ca| %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/stacks.yml.erb:stacks: <%= p("cc.stacks", []).to_yaml.gsub("---", "") %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/local_blobstore_downloads.conf.erb:<% if p("cc.packages.blobstore_type").downcase == "fog" && p("cc.packages.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/local_blobstore_downloads.conf.erb:<% if p("cc.droplets.blobstore_type").downcase == "fog" && p("cc.droplets.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/jobs/cloud_controller_ng/templates/local_blobstore_downloads.conf.erb:<% if p("cc.buildpacks.blobstore_type").downcase == "fog" && p("cc.buildpacks.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/shared_job_templates/setup_local_blobstore.sh.erb:  <% if p("cc.packages.blobstore_type").downcase == "fog" && p("cc.packages.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/shared_job_templates/setup_local_blobstore.sh.erb:  <% if p("cc.resource_pool.blobstore_type").downcase == "fog" && p("cc.resource_pool.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/shared_job_templates/setup_local_blobstore.sh.erb:  <% if p("cc.droplets.blobstore_type").downcase == "fog" && p("cc.droplets.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/shared_job_templates/setup_local_blobstore.sh.erb:  <% if p("cc.buildpacks.blobstore_type").downcase == "fog" && p("cc.buildpacks.fog_connection.provider", "").downcase == "local" %>
./src/capi-release/src/cloud_controller_ng/bosh/shared_job_templates/stacks.yml.erb:stacks: <%= p("cc.stacks", []).to_yaml.gsub("---", "") %>
```

**Comment by cppforlife** [comment]
all righty. thank you for convincing me.

**Pull request merged**
