### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by michaellihs**

### CODE REVIEW

**Comment by chipchilders** [comment]
open / close to check CLA

**Comment by chipchilders** [comment]
open / close to check CLA

**Comment by chipchilders** [comment]
open / close to check CLA

**Comment by chipchilders** [comment]
open / close to check CLA

**Comment by chipchilders** [comment]
weird ... anyway, this contributor has submitted a CLA. This can be accepted.

**Comment by michaellihs** [comment]
sorry for all this trouble for just adding an "a" to a documentation file... hope to make more contributions in the near future :-)

**Comment by chipchilders** [comment]
once more with feeling - CLA bot check time!

**Comment by chipchilders** [comment]
once more with feeling - CLA bot check time!

**Comment by chipchilders** [comment]
@michaellihs thanks! The team will come around to this in time.

**Pull request merged**
