### PR TITLE
fix minor issues for cliv2 commands page

### PR DESCRIPTION
**Pull request by fredwangwang**
image

### CODE REVIEW

**Comment by fredwangwang** [comment]
More changes than originally found, so changed the PR title as well.

changelog:

* fix styling for delete-env
* dix styling for remove-blob
* Combine `#### Environment {: #environment }` with `### Director Environment {: #director-env}`. They are the same info in two places

**Comment by mrosecrance** [comment]
I think this PR may have only have half of your changes. I see the deduplication for Environment but not the rest of it.

**Comment by fredwangwang** [comment]
It is complete. The Newline added before/after the `remove-blob` and `delete-env` fix the styling issue when rendered by mkdocs

image
image

**Comment by belinda-liu** [comment]
Thanks for the fix!

@belinda-liu && @mrosecrance, CF BOSH team

**Pull request merged**
