### PR TITLE
Fix a link to Resource Pool in Terminology

### PR DESCRIPTION
**Pull request by wlindner**

### CODE REVIEW

**Comment by wlindner** [comment]
I made my organization membership to cloudfoundry public, so I should no longer need to sign the CLA.

**Comment by dpb587-pivotal** [comment]
I think `resource-pools` was the correct form? It's linked from other lines in the file there, too?

**Comment by cppforlife** [comment]
@wlindner plural is correct here. is there a link that points to #resource-pool somewhere?

**Comment by wlindner** [comment]
@dpb587-pivotal @cppforlife my mistake, I made the change in the wrong place. Here's the PR for fixing the link: #74

**Pull request closed without merging**
