### PR TITLE
Fix incorrect cloud config statement

### PR DESCRIPTION
**Pull request by zmb3**
Director 257+ allows for both V1 and V2 manifests.

### CODE REVIEW

**Comment by zmb3** [comment]
Should be covered under the Pivotal CLA, right?

**Comment by dpb587-pivotal** [comment]
Should be fine. If you publish one of your Pivotal/CF organizations to your profile, @cfdreddbot will be a little less annoyed :)

**Comment by zmb3** [comment]
Is being in the **pivotalservices** org not sufficient?

image

**Comment by dpb587-pivotal** [comment]
You're a member, but they're not actually public - just visible to you when logged in. Visit the individual orgs and go to the People tab to find yourself and the option to make your membership public. The public membership is what @cfdreddbot goes off of.

**Comment by zmb3** [comment]
Ah, got it! Thanks for the pointer.  I made them public now.

**Comment by dpb587-pivotal** [comment]
@cfdreddbot agrees - thanks!

**Pull request merged**
