### PR TITLE
Fix documentation typo about vars-env flag

### PR DESCRIPTION
**Pull request by MattSurabian**
Was reviewing these docs with a coworker and noticed this typo.

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
cc @chipchilders to check on a @Zipcar corporate CLA that @MattSurabian should be covered by.

Merging as simple typo fix regardless.

Thanks!

**Comment by chipchilders** [comment]
@dpb587 it was fine to merge this without a CLA for a small change like that. :)

@MattSurabian we are unable to find any indication that ZipCar has a CLA on file with the CFF. Any chance you know who may have sent it to us?

**Comment by blondbaron** [comment]
Hey Chip, let me see if I can find the CLA. I could have sworn i took care of it before Summit this year.

-Andy Rosequist

**Comment by MattSurabian** [comment]
Should have been Andy Rosequist (@blondbaron) on behalf of the Zipcar github org which I'm a public member of.

**Comment by chipchilders** [comment]
@blondbaron just checked our inboxes and records... no sight of a zipcar CLA. If you find it, could you sent it to contributors@cloudfoundry.org please?

**Pull request merged**
